title: Image Tools
url: https://enheragu.github.io
baseurl: /image-tools

plugins:
  - jekyll-remote-theme

remote_theme: enheragu/tool-pages-theme

shared_assets_base: /image-tools/assets/shared

defaults:
  - scope:
      path: ""
      type: pages
    values:
      lang: en
      compact_mode: true
      project: image-tools
      tool_name: Image Tools
      analytics_measurement_id: G-NB38N7JG5S
      footer_related_contextual: true
      with_tabs: true
      with_tools_nav: true
  - scope:
      path: "HarrisShutter"
    values:
      header_supertitle: Image Tools
      tool_name: HarrisShutter
      with_image_card: true
      with_lightbox_stage: true
  - scope:
      path: "ChronoSync"
    values:
      header_supertitle: Image Tools
      tool_name: ChronoSync
